---
title: "METABRIC Gene Expression"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Importing all the requisite packages first.
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(readr)
library(broom)
library(caret)
library(glmnet)
library(glmnetUtils)
library(foreach)
```

Some requisite functions.
```{r}
# To transpose function

# To perform ANOVA
```

# Importing data

```{r}
colnames <- read_delim("../../../metabric/EGAF00000102986/discovery_ExpressionMatrix.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE, n_max = 1, col_names = FALSE)
colnames <- c("genes", as.character(colnames[1,]))

discovery <- read_delim("../../../metabric/EGAF00000102986/discovery_ExpressionMatrix.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE, col_names = colnames, skip = 1)

colnames <- read_delim("../../../metabric/EGAF00000102987/validation_ExpressionMatrix.txt", 
    " ", escape_double = FALSE, trim_ws = TRUE, n_max = 1, col_names = FALSE)
colnames <- c("genes", as.character(colnames[1,]))

validation <- read_delim("../../../metabric/EGAF00000102987/validation_ExpressionMatrix.txt", 
    " ", escape_double = FALSE, trim_ws = TRUE, col_names = colnames, skip = 1)

rm(colnames)
```


Converting the Illumina Gene IDs to Gene Symbols
```{r}
# BiocManager::install("illuminaHumanv3.db")
library(illuminaHumanv3.db)
genes <- discovery$genes
genes <- data.frame(Gene=unlist(mget(x = genes, envir = illuminaHumanv3ENTREZREANNOTATED)))

discovery$genes <- genes$Gene

genes <- validation$genes
genes <- data.frame(Gene=unlist(mget(x = genes, envir = illuminaHumanv3ENTREZREANNOTATED)))

validation$genes <- genes$Gene
rm(genes)
```
Removing NAs and summarising over duplicates
```{r}
discovery <- discovery[complete.cases(discovery), ] %>%
      group_by(genes) %>%
      summarize(across(everything(), list(mean))) #%>%
#      remove_rownames() %>%
#      column_to_rownames("genes")

validation <- validation[complete.cases(validation), ] %>%
      group_by(genes) %>%
      summarize(across(everything(), list(mean))) #%>%
#      remove_rownames() %>%
#      column_to_rownames("genes")

```

Reading in the requisite genes from the TCGA selected genes
```{r}
brca_genes <- read_csv("../TCGA BRCA/mrna_top1000.csv", n_max = 1, col_names = FALSE)

brca_genes <- as.character(brca_genes[,2:1001])
brca_genes <- unlist(str_split(brca_genes, "\\|"))[ c(FALSE, TRUE) ]

# metabric_genes <- as.character(discovery$genes)
# length(intersect(brca_genes, metabric_genes))
# length(setdiff(brca_genes, metabric_genes))
# setdiff(brca_genes, metabric_genes)
```

Selecting only those features selected for brca
```{r}
metabric_d <- discovery %>%
  filter(genes %in% brca_genes) %>%
  remove_rownames() %>%
  column_to_rownames("genes")

metabric_v <- validation %>%
  filter(genes %in% brca_genes) %>%
  remove_rownames() %>%
  column_to_rownames("genes")

setdiff(metabric_d$genes, metabric_v$genes)
```

Transposing and saving to files
```{r}
transpose_df <- function(df) {
  t_df <- data.table::transpose(df)
  colnames(t_df) <- rownames(df)
  rownames(t_df) <- colnames(df)
  t_df <- t_df %>%
    tibble::rownames_to_column(.data = .) %>%
    tibble::as_tibble(.)
  return(t_df)
}

transpose_df(metabric_d) %>%
  dplyr::rename(patient_id = "rowname") %>%
  write.csv("metabric_discovery.csv", row.names = FALSE)

transpose_df(metabric_v) %>%
  dplyr::rename(patient_id = "rowname") %>%
  write.csv("metabric_validation.csv", row.names = FALSE)
```

