---
title: "Data Preliminaries"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggfortify)

# To transpose
transpose_df <- function(df) {
  t_df <- data.table::transpose(df)
  colnames(t_df) <- rownames(df)
  rownames(t_df) <- colnames(df)
  t_df <- t_df %>%
    tibble::rownames_to_column(.data = .) %>%
    tibble::as_tibble(.)
  return(t_df)
}
```

## Loading data
```{r message=FALSE, warning=FALSE}
data.top1000 <- read_csv("metabric_mrna_common_genes.csv")

colnames <- read_delim("../../../metabric/EGAF00000102986/discovery_ExpressionMatrix.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE, n_max = 1, col_names = FALSE)
colnames <- c("genes", as.character(colnames[1,]))

discovery <- read_delim("../../../metabric/EGAF00000102986/discovery_ExpressionMatrix.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE, col_names = colnames, skip = 1)

colnames <- read_delim("../../../metabric/EGAF00000102987/validation_ExpressionMatrix.txt", 
    " ", escape_double = FALSE, trim_ws = TRUE, n_max = 1, col_names = FALSE)
colnames <- c("genes", as.character(colnames[1,]))

validation <- read_delim("../../../metabric/EGAF00000102987/validation_ExpressionMatrix.txt", 
    " ", escape_double = FALSE, trim_ws = TRUE, col_names = colnames, skip = 1)

labels_discovery <- read_delim("clinical_data_discovery.txt", "\t") %>% 
                      dplyr::rename(patient_id = METABRIC_ID, cancer_subtype = Pam50Subtype)
labels_validation <- read_delim("clinical_data_validation.txt", "\t") %>% 
                      dplyr::rename(patient_id = METABRIC_ID, cancer_subtype = Pam50Subtype)
rm(colnames)
```

Converting the Illumina Gene IDs to Gene Symbols
```{r message=FALSE, warning=FALSE}
library(illuminaHumanv3.db)
genes <- discovery$genes
genes <- data.frame(Gene=unlist(mget(x = genes, envir = illuminaHumanv3ENTREZREANNOTATED)))

discovery$genes <- genes$Gene

genes <- validation$genes
genes <- data.frame(Gene=unlist(mget(x = genes, envir = illuminaHumanv3ENTREZREANNOTATED)))

validation$genes <- genes$Gene
rm(genes)
```

Removing NAs and summarising over duplicates
```{r}
discovery <- discovery[complete.cases(discovery), ] %>%
      group_by(genes) %>%
      summarize(across(everything(), list(mean)))

validation <- validation[complete.cases(validation), ] %>%
      group_by(genes) %>%
      summarize(across(everything(), list(mean)))
```

## Filtering data
```{r}
common_genes <- intersect(discovery$genes, validation$genes)

metabric_d <- discovery %>%
  filter(genes %in% common_genes) %>%
  remove_rownames() %>%
  column_to_rownames("genes")

metabric_v <- validation %>%
  filter(genes %in% common_genes) %>%
  remove_rownames() %>%
  column_to_rownames("genes")

setdiff(metabric_d$genes, metabric_v$genes)

clinical <- rbind(labels_discovery, labels_validation)
toBeRemoved <- clinical$patient_id[clinical$cancer_subtype == "NC"]
clinical <- filter(clinical, !patient_id %in% toBeRemoved)

metabric_d <- transpose_df(metabric_d) %>%
  dplyr::rename(patient_id = "rowname")
metabric_d$patient_id <- unlist(str_split(metabric_d$patient_id, "\\_"))[c(TRUE, FALSE)]

metabric_d <- filter(metabric_d, !patient_id %in% toBeRemoved)

metabric_v <- transpose_df(metabric_v) %>%
  dplyr::rename(patient_id = "rowname")
metabric_v$patient_id <- unlist(str_split(metabric_v$patient_id, "\\_"))[c(TRUE, FALSE)]

metabric_v <- filter(metabric_v, !patient_id %in% toBeRemoved)

data <- rbind(metabric_d, metabric_v)
```

## Processing
```{r}
meta_and_data <- left_join(data, clinical, by = "patient_id") %>%
  mutate(Site = as.factor(Site)) %>%
  dplyr::rename(Subtype = cancer_subtype,
                Age = age_at_diagnosis,
                Cellularity = cellularity)

meta_and_data$Set <- NULL
meta_and_data$Set[meta_and_data$patient_id %in% metabric_d$patient_id] = "Discovery"
meta_and_data$Set[meta_and_data$patient_id %in% metabric_v$patient_id] = "Validation"
```


## Performing Principal Component Analysis

```{r}
metabric.pca <- prcomp(data[,c(2:19871)], center = TRUE, scale. = TRUE)
str(metabric.pca)

metabric.top1000.pca <- prcomp(data.top1000[,c(2:954)], center = TRUE, scale. = TRUE)
str(metabric.top1000.pca)
```


## Checking for covairates

### Tissue and Clinical Data Source Site

```{r}
autoplot(metabric.pca, data=meta_and_data, colour="Site", frame=TRUE, frame.type="norm") +
  labs(title = "PCA on scaled data, coloured based on tissue source site")
```

### Treatment Received

```{r}
autoplot(metabric.pca, data=meta_and_data, colour="Treatment", frame=TRUE, frame.type="norm") +
  labs(title = "PCA on scaled data, coloured based on Treatment Received")
```

### Cancer Subtype
```{r}
autoplot(metabric.pca, data=meta_and_data, colour="Subtype", frame=TRUE, frame.type="norm") +
  labs(title = "PCA on scaled data, coloured based on Breast Cancer Subtype")
```

### Age
```{r}
autoplot(metabric.pca, data=meta_and_data, colour="Age", frame=TRUE, frame.type="norm") +
  labs(title = "PCA on scaled data, coloured based on Age")
```

### Cancer Cellularity
```{r}
autoplot(metabric.pca, data=meta_and_data, colour="Cellularity", frame=TRUE, frame.type="norm") +
  labs(title = "PCA on scaled data, coloured based on Cancer Cellularity")
```


